### ISSUE TITLE
-----------------------------------

### ISSUE THREAD

**Issue by ghost** [ET-Lang/Book#28]
--------------

**Comment by BaseMax** [comment]
Hey,
Thank you. @pglapds 

> http://github.com/et

It's an active account, I think we can not get it. @et

----------

https://github.com/ET-Lang/Book
https://github.com/ET-Lang/book

Both are the same. (You can test and enter it on your browser address bar)

Regards,
Max

**Comment by pglapds** [comment]
> 
> 
> Hey,
> Thank you. @pglapds
> 
> > [http://github.com/et](https://github.com/et)
> 
> It's an active account, I think we can not get it. @et
> 
> https://github.com/ET-Lang/Book
> https://github.com/ET-Lang/book
> 
> Both are the same. (You can test and enter it on your browser address bar)
> 
> Regards,
> Max

Thank.

**Comment by pglapds** [comment]
### Code URL


**Before:** github.com/et/Book ,  **After :** github.com/et/book

**Examples**
      1. With  Consistent URL** ----------: github.com/et/book
      2. URL not consistent** ---- ^ -----: github.com/et/Book

###   Changes

1. url path: **before**: /Book
2. url path: **after**: /book

**Comment by et** [comment]
Hey all,
Sorry but I really like my account name. It’s been my alias for about twenty years.
Cool project though 😊

**Comment by BaseMax** [comment]
Hey Eric Thomas,

Yeah, it's true.
Thanks for your answer.

I've invited **Eric Thomas** to **ET Programming Language**! They'll be receiving an email shortly. @et

> Invitations are sent via email and can be accepted at https://github.com/ET-Lang

Regards,
Max
