### ISSUE TITLE
--------------------

### ISSUE THREAD

**Issue by ghost** [ET-Lang/Book#34]
----------------------------

**Comment by pglapds** [comment]
**& @ warning: ----**

### Objective

1. Describe simple and add anchor or no.

**Comment by pglapds** [comment]
<br>
<br>
<br>

**& @ design: ----**

### Objective

1. Describe simple and add anchor or no.


<br>
<br>
<br>

**Comment by pglapds** [comment]
<br>
<br>
<br>

**& @ changes: ----**

### Objective

1. Describe simple and add anchor or no.

1. Describe simple and add anchor or no.

1. Describe simple and add anchor or no.

<br>
<br>
<br>

**Comment by pglapds** [comment]
<br>
<br>
<br>

**& @ drafts: ----**

### Objective

1. Describe simple and add anchor or no.

1. Describe simple and add anchor or no.

1. Describe simple and add anchor or no.

<br>
<br>
<br>

**Comment by pglapds** [comment]
<br>
<br>
<br>

**& @ error: ----**

### Objective

1. Describe simple and add anchor or no.

1. Describe simple and add anchor or no.

1. Describe simple and add anchor or no.

<br>
<br>
<br>

**Comment by pglapds** [comment]
<br>
<br>
<br>

**& @ remove: ----**

### Objective

1. Describe simple and add anchor or no.

1. Describe simple and add anchor or no.

1. Describe simple and add anchor or no.

<br>
<br>
<br>

**Comment by pglapds** [comment]
<br>
<br>
<br>

**& @ update: ----**

### Objective

1. Describe simple and add anchor or no.

1. Describe simple and add anchor or no.

1. Describe simple and add anchor or no.

<br>
<br>
<br>

**Comment by pglapds** [comment]
<br>
<br>
<br>

**& @ t: ----**

### Objective

1. Describe simple and add anchor or no.

1. Describe simple and add anchor or no.

1. Describe simple and add anchor or no.

<br>
<br>
<br>

**Comment by pglapds** [comment]
Keywords:

### 1. **t: transition , transform.** 

Describe: A file that is going to be changed but needs to be parsed.


### 2. **change:**

Describe: A file that is going to be changed but needs to be parsed.

### 3. **changes:**

Describe: A file that is going to be changed but needs to be parsed.


### 4. **remove:**

Describe: Alert on the feature or something that will be removed.


### 5. **update:**

Describe: Alert about the feature or something that will be updated.

**Comment by pglapds** [comment]
Report on change. 

**Example**

**& @ change: ----**


### Objective

 1. Describe simple and add anchor or no. Lorem ipsum ...

**Comment by pglapds** [comment]
@ is reference , @ link  or @ symbol ... input, output too &
