### ISSUE TITLE
----------------

### ISSUE THREAD

**Issue by ghost** [ET-Lang/Book#40]
----------------------------------

**Comment by pglapds** [comment]
## Example & Use

<br>
<br>

**Example 1** , **1.** Evolution,  **Concept** 

![Ampersand_Evolution2](https://user-images.githubusercontent.com/46846354/58900400-7c1de200-86d5-11e9-938f-1cbd52ab2142.png)

Evolution: Alpha **->** Beta **->**  Dev **->** Stable **->** Release. 

<br>
<br>

**//** Or versions: Build, Rebuild, Revision.... 

<br>
<br>

**Example 2** , **2.** Evolution,  **Use, Shell** 

1. > 1. & , normal use
2. > 2. :&:  , see errors 
3. > 3. :& , acess settings
4. > 4. &: , acess url 
5. > 5. -&- , acess settings design
6. > 6.  _&_ , acess protocol
7. > 7. et , acess & run file
9. > 9.  _et_  , acess & run file in cloud
10. > 10.  -et-  , docs & examples
11. > 11.  :et , repl 
12. > 12.  :et: , save 
13. > 13.  et: , transfer 
14. > 14.  .et: , user and password
15. > 15.  .et . , class, methods, special use
16. > 16.  :et . , libs
17. > 17.  et: . , process 
18. > 18.  .&:  , sys
19. > 19.  .& . , io 
20. > 20.  :& . , folder
21. > 21.  &: . , user, hostname, host, localhost, ip... 


<br>
<br>

**Comment by BaseMax** [comment]
Hey,

Fine, We should think about it.

Regards,
Max

**Comment by ghost** [comment]
> 
> Hey, Fine, We should think about it. Regards, Max

Thank. **^^**

**Comment by BaseMax** [comment]
> > Hey, Fine, We should think about it. Regards, Max
> 
> Thank. **^^**

Currently, we should continue to develop and write a book. :+1:

**Comment by pglapds** [comment]
> Currently, we should continue to develop and write a book.

Yeah.
